### Numpy array and basics

In [33]:
import numpy as np
import time 

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [ ]:
# making python list 
py_list = [1, 2, 3, 4, 5]
## here the list will be copied the number of times you multiply it
print("Python list Multiplication : ", py_list * 2)

# making python array also called numpy array 
np_array = np.array([1, 2, 3, 4, 5])
## here the multiplication is done element-wise
print("python array Multiplication: ", np_array * 2)

start = time.time()
time_list = [i*2 for i in range(1000000)]
print("\nList: ", time_list[:5])
print("List operation time: ", time.time() - start)

start = time.time()
# the arange is used for creating array which includes integers under specific range .. it includes three things - start end step 
time_array = np.arange(1000000) * 2 
print("\nArray: ", time_array[:5])
print("Array operation time: ", time.time() - start)

Python list Multiplication :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array Multiplication:  [ 2  4  6  8 10]

List:  [0, 2, 4, 6, 8]
List operation time:  0.08499407768249512

Array:  [0 2 4 6 8]
Array operation time:  0.004007101058959961


### Creating array from scratch


In [ ]:
# for creating a array with only zeros 
zeros = np.zeros((3,4)) # we provide the dimension of the array 
print("\nZeros Array: \n", zeros)

# for creating a array with only ones
ones = np.ones((3, 4)) # it also take the dimesnion of the array 
print("\nOnes Array: \n", ones)

# for creating an array with the specific constant value 
constant = np.full((3,4), 7)
print("\nconstant array: \n", constant)

# this will give the matrix of random values .. the values are between 0 and 1
random = np.random.random((3,4))
print("\nRandom Array: \n", random)


Zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

constant array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Random Array: 
 [[0.55311676 0.20824565 0.53871153 0.90317324]
 [0.75865019 0.88135017 0.95838682 0.31232653]
 [0.31599868 0.41023869 0.23503853 0.86861714]]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
print("\nVector: ", vector)

# for creating a 2D matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix: \n", matrix)

# for creating a tensor
# a matrix having more than 2 dimensions is called tensor
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nTensor: \n", tensor)


Vector:  [1 2 3]

Matrix: 
 [[1 2 3]
 [4 5 6]]

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

# for getting the shape of the array .. shape is the number of rows and columns in the array
# first rows and them columns
print("\nShape of the array: ", arr.shape)

# for getting the number of dimensions of the array 
print("Number of dimensions: ", arr.ndim)

# for getting the size of the array .. size is the total number of elements in the array 
print("Size of the array: ", arr.size)

# for getting the data type of the array 
# generally it is considered to use single data type for the array 
print("Data type of the array: ", arr.dtype)


Shape of the array:  (2, 3)
Number of dimensions:  2
Size of the array:  6
Data type of the array:  int64


### Array Reshaping


In [ ]:
arr = np.arange(1, 11)
print("\nArray for slicing: ", arr)

# we only can reshape the array if the total number of elements in the array is equal to the total number of elements in the reshaped array
reshaped = arr.reshape(5, 2)  # reshaping the array to 5 rows and 2 columns
print("Reshaped Array: \n", reshaped)

# for getting the transpose of the array
transposed = reshaped.T  # transposing the reshaped array
print("Transposed Array: \n", transposed)

# to make a matrix into the 1D array 
flatterned = arr.flatten()  # converting the array to 1D
print("Flattened Array: ", flatterned)

# ravel is used to convert the multi-dimensional array into 1D array 
# but it will return a view of the original array if possible
raveled = reshaped.ravel() 
print("Raveled Array: ", raveled)



Array for slicing:  [ 1  2  3  4  5  6  7  8  9 10]
Reshaped Array: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transposed Array: 
 [[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
Flattened Array:  [ 1  2  3  4  5  6  7  8  9 10]
Raveled Array:  [ 1  2  3  4  5  6  7  8  9 10]
