### Numpy Array Operations


In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)
print("Basic Slicing: ", arr[2:7])
print("With step: ", arr[1:8:2])
print("Negative indices: ", arr[-3])

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indices:  8


In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr_2d)
print("Specific element :", arr_2d[1, 2])  # Element at row 1, column 2
print("Row slicing: ", arr_2d[1, :])  # All columns of row 1
print("Column slicing: ", arr_2d[:, 1])  # All rows of column 1
print("Sub-array slicing: ", arr_2d[0:2, 1:3])  # Rows 0-1 and columns 1-2

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element : 6
Row slicing:  [4 5 6]
Column slicing:  [2 5 8]
Sub-array slicing:  [[2 3]
 [5 6]]


### Sorting

In [7]:
# sorting a 1D array

unsorted = np.array([3, 1, 4, 2, 4, 9, 4, 5, 7, 0, 6, 8])
print("Unsorted array:", unsorted)

# this will not change the original array and just print the sorted result 
# if you print the unsorted array again, it will still be unsorted
sortedArray = np.sort(unsorted)
print("Sorted array (not in-place): ", sortedArray)
#print("Original array after sorting: ", unsorted)

# this will change the original array and make it sorted and return none
# if you print the unsorted array again, it will be sorted
# unsorted.sort()
# print("Sorted array (in-place) and the original array: ", unsorted)

# now we want to sort the array in descending order
sortedArrayDesc = np.sort(unsorted)[::-1]
print("Sorted array in descending order (not in-place): ", sortedArrayDesc)




# Sorting a 2D array

unsorted_2d = np.array([[3, 1, 4], [2, 4, 9], [4, 5, 7], [2, 6, 8]])
print("Unsorted 2D array:\n", unsorted_2d)

# Note: This sorts each column independently
sorted_2d_cols = np.sort(unsorted_2d, axis=0)  # Sort along columns
print("Sorted 2D array along columns:\n", sorted_2d_cols)
sorted_2d_desc_cols = sorted_2d_cols[::-1] # each column in descending order
print("Sorted 2D array along columns in descending order:\n", sorted_2d_desc_cols)

# sorting on the basis of first column 
sorted_2d_first_col = unsorted_2d[unsorted_2d[:, 0].argsort()]
print("Sorted 2D array based on first column:\n", sorted_2d_first_col)

# Note: This sorts each row independently
sorted_2d_rows = np.sort(unsorted_2d, axis=1)  # Sort along rows
print("Sorted 2D array along rows:\n", sorted_2d_rows)
sorted_2d_desc_rows = sorted_2d_rows[:, ::-1]  # each row in descending order
print("Sorted 2D array along rows in descending order:\n", sorted_2d_desc_rows)

# sorting on the basis of first row 
sorted_2d_first_row = unsorted_2d[:, unsorted_2d[0, :].argsort()]
print("Sorted 2D array based on first row:\n", sorted_2d_first_row)


Unsorted array: [3 1 4 2 4 9 4 5 7 0 6 8]
Sorted array (not in-place):  [0 1 2 3 4 4 4 5 6 7 8 9]
Sorted array in descending order (not in-place):  [9 8 7 6 5 4 4 4 3 2 1 0]
Unsorted 2D array:
 [[3 1 4]
 [2 4 9]
 [4 5 7]
 [2 6 8]]
Sorted 2D array along columns:
 [[2 1 4]
 [2 4 7]
 [3 5 8]
 [4 6 9]]
Sorted 2D array along columns in descending order:
 [[4 6 9]
 [3 5 8]
 [2 4 7]
 [2 1 4]]
Sorted 2D array based on first column:
 [[2 4 9]
 [2 6 8]
 [3 1 4]
 [4 5 7]]
Sorted 2D array along rows:
 [[1 3 4]
 [2 4 9]
 [4 5 7]
 [2 6 8]]
Sorted 2D array along rows in descending order:
 [[4 3 1]
 [9 4 2]
 [7 5 4]
 [8 6 2]]
Sorted 2D array based on first row:
 [[1 3 4]
 [4 2 9]
 [5 4 7]
 [6 2 8]]


### Filter

In [8]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# even number from the array 
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_numbers)


Even Numbers:  [ 2  4  6  8 10]


### Filter by Mask

In [9]:
mask = numbers % 2 != 0
odd_numbers = numbers[mask]
print("Odd numbers: ", odd_numbers)


Odd numbers:  [1 3 5 7 9]


### Fancy indexing vs np.where()

In [10]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where: ", numbers[where_result])

[1 3 5]
NP where:  [ 6  7  8  9 10]


### condition array

In [ ]:
condition_array = np.where(numbers > 5)
print("Condition_array: ", condition_array)

# the where clause is work as the if else statement 
# like if the conditon full fill then some thing would happen if not then something would happen

condition_array = np.where(numbers > 5, numbers, numbers*2)
# so in this the numbers which are greater then 5 would remain as it is and the numbers which are smaller then 5 would be multiplied by 2
print("Condition array: ", condition_array)

Condition_array:  (array([5, 6, 7, 8, 9]),)
Condition array:  [ 2  4  6  8 10  6  7  8  9 10]


### Adding and Removing of data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# this will do the array addition
combined = arr1 + arr2
print(combined)
#[5 7 9]

# for concatination
concatination = np.concatenate((arr1, arr2))
print(concatination)
#[1 2 3 4 5 6]



[5 7 9]
[1 2 3 4 5 6]


### Array compatibility

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatability Shapes: ", a.shape == b.shape)

Compatability Shapes:  False


In [25]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
new_col = np.array([[9],[8]])

## this will add the col and row on the last index
# for adding a new row 
with_new_row = np.vstack((original, new_row))
print(with_new_row)

# for adding a new col
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 9]
 [3 4 8]]


In [ ]:
## for deleting 

# here we are deleting any index element in the 1D array
ar1 = np.array([1,2,3,4,5,6])
deleted1 = np.delete(arr1, 2)
print("Array after deletion: ", deleted1)

# here we want to delete any row in the 2D array 
# in the 2D array it will flattern the array and then delete normal deltion with the indexing 
arr2 = np.array([[1,2,3], [4,5,6]])
deleted2 = np.delete(arr2, 1)


Array after deletion:  [1 2]
[[1 2 3]
 [4 5 6]]
[1 3 4 5 6]
